name: Build and Publish
on:
  push:
    branches: [ master ]
env:
  JEKYLL_ENV: production    
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.4

      - name: Install Dependencies
        run: |
          sudo apt-get update 
          sudo apt-get install -y imagemagick curl xz-utils
          gem install bundler -v 2.5
          bundler install

      - name: Install Typst
        run: |
          curl -L -k https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-musl.tar.xz -o _typst.tar.xz
          tar -xf _typst.tar.xz
          sudo mv typst-x86_64-unknown-linux-musl/typst /usr/local/bin/typst
          sudo chmod +x /usr/local/bin/typst

      - name: Build gh-pages
        run: bundle exec jekyll build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId:  ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: henrikbecker
          directory: _site        

      - name: Publish gh-pages
        if: false
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: _site
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

       
